### ISSUE TITLE
Simplify blog content & styling

### ISSUE THREAD

**Issue by JayAchar** [JayAchar/jayachar.github.io#18]
# Problem

The blog component of the site needs to be simplified since it will only contain the blog itself and no additional information. 

# Ideas

https://nourisheats.co/

# Tasks

- [ ] Center all content
- [ ] Remove personal picture and title etc....
- [ ] Include some links at bottom of page
